export type BlockedTerm = {
  pattern: RegExp;
  reason: string;
};

// TODO: move to DB later.
export const BLOCKED_TERMS: BlockedTerm[] = [
  { pattern: /\bnigg(?:er|a)s?\b/i, reason: "hate_speech" },
  { pattern: /\bspic(?:s)?\b/i, reason: "hate_speech" },
  { pattern: /\bkike(?:s)?\b/i, reason: "hate_speech" },
  { pattern: /\bchink(?:s)?\b/i, reason: "hate_speech" },
  { pattern: /\bgook(?:s)?\b/i, reason: "hate_speech" },
  { pattern: /\bwetback(?:s)?\b/i, reason: "hate_speech" },
  { pattern: /\bcoon(?:s)?\b/i, reason: "hate_speech" },
  { pattern: /\braghead(?:s)?\b/i, reason: "hate_speech" },
  { pattern: /\bpaki(?:s)?\b/i, reason: "hate_speech" },
  { pattern: /\bgypsy(?:s)?\b/i, reason: "hate_speech" },
  { pattern: /\bnegr(?:o|i|u|a)?\b/i, reason: "hate_speech" },
  { pattern: /\bne3r(?:o|i|u|a)?\b/i, reason: "hate_speech" },
  { pattern: /\bcikan\w*\b/i, reason: "hate_speech" },
  { pattern: /\bcigan\w*\b/i, reason: "hate_speech" },
  { pattern: /\bfag(?:got|s)?\b/i, reason: "hate_speech" },
  { pattern: /\bdyke(?:s)?\b/i, reason: "hate_speech" },
  { pattern: /\btrann(?:y|ies)\b/i, reason: "hate_speech" },
  { pattern: /\bshemale(?:s)?\b/i, reason: "hate_speech" },
  { pattern: /\bbuzerant\w*\b/i, reason: "hate_speech" },
  { pattern: /\bbuzn\w*\b/i, reason: "hate_speech" },
  { pattern: /\bbuzik\w*\b/i, reason: "hate_speech" },
  { pattern: /\bhomous\w*\b/i, reason: "hate_speech" },
  { pattern: /\btepl(?:os|ous|ousek|ousi|ousu)\w*\b/i, reason: "hate_speech" },
  { pattern: /\bkreten\w*\b/i, reason: "harassment" },
  { pattern: /\bzmrd\w*\b/i, reason: "harassment" },
  { pattern: /\bkokot\w*\b/i, reason: "harassment" },
  { pattern: /\bcurak\w*\b/i, reason: "harassment" },
  { pattern: /\bpica\w*\b/i, reason: "harassment" },
  { pattern: /\bkund\w*\b/i, reason: "harassment" },
  { pattern: /\bsvin\w*\b/i, reason: "harassment" },
  { pattern: /\bkill\s+all\b/i, reason: "violence" },
  { pattern: /\bkill\s+them\b/i, reason: "violence" },
  { pattern: /\bdeath\s+to\b/i, reason: "violence" },
  { pattern: /\bgas\s+the\b/i, reason: "violence" },
  { pattern: /\bexterminate\b/i, reason: "violence" },
  { pattern: /\bgenocide\b/i, reason: "violence" },
  { pattern: /\blynch\b/i, reason: "violence" },
  { pattern: /\bhang\s+them\b/i, reason: "violence" },
  { pattern: /\bshoot\s+up\b/i, reason: "violence" },
  { pattern: /\bslaughter\b/i, reason: "violence" },
  { pattern: /\bheil\s+hitler\b/i, reason: "extremism" },
  { pattern: /\bsieg\s+heil\b/i, reason: "extremism" },
  { pattern: /\bwhite\s+power\b/i, reason: "extremism" },
  { pattern: /\bblood\s+and\s+soil\b/i, reason: "extremism" },
  { pattern: /\b14\s*88\b/i, reason: "extremism" },
  { pattern: /\b1488\b/i, reason: "extremism" },
  { pattern: /\bkkk\b/i, reason: "extremism" },
  { pattern: /\bfree\s+money\b/i, reason: "spam" },
  { pattern: /\bmake\s+money\s+fast\b/i, reason: "spam" },
  { pattern: /\bget\s+rich\s+quick\b/i, reason: "spam" },
  { pattern: /\bwork\s+from\s+home\b/i, reason: "spam" },
  { pattern: /\bclick\s+here\b/i, reason: "spam" },
  { pattern: /\bcasino\b/i, reason: "spam" },
  { pattern: /\bxxx\b/i, reason: "spam" },
  { pattern: /\bviagra\b/i, reason: "spam" },
  { pattern: /\bcrypto\s+giveaway\b/i, reason: "spam" },
  {
    pattern:
      /(?:https?:\/\/)?(?:bit\.ly|t\.co|tinyurl\.com|goo\.gl|ow\.ly|cutt\.ly|is\.gd|buff\.ly|rebrand\.ly|shorturl\.at)\b/i,
    reason: "spam",
  },
];
